title: WT-Stats
author: celebhen

description: >
  WT-Stats analysiert Abstimmungsdaten und erhÃ¶ht die Transparenz des Projekt WahreTabelle.de und seiner Nutzer.

show_excerpts: true

minima:
  date_format: "%d. %b. %Y"

  social_links:
    rss: rss

header_pages:
 - search.html
 - about.html

theme: minima

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
